name: Build Docker Image

on:
  push:  
    branches:    
      - master
    tag:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: undefined

    steps:
    - name: init IMAGE_TAG dev
      if: startsWith(github.ref,'refs/heads/master')
      run: echo "::set-env name=IMAGE_TAG::latest-dev"

    - name: init IMAGE_TAG stage
      if: startsWith(github.ref,'refs/heads/stage-')
      run: |
        TAG=$(cut -d "-" -f2 <<< "$GITHUB_REF")-dev
        echo "::set-env name=IMAGE_TAG::${TAG}"
      
    - name: init IMAGE_TAG release
      if: startsWith(github.ref,'refs/heads/release')
      run: echo "::set-env name=IMAGE_TAG::release"

    # - name: init IMAGE_TAG git tag
    #   if: $IMAGE_TAG == 'undefined'
    #   run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF/refs\/tags\//}"

    - name: Build the Docker image
      if: endsWith(env.IMAGE_TAG,'-dev')
      run: echo "docker tag is $IMAGE_TAG"

